// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

// 定义生成service的包名

package myserver

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"id,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=Limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserReq) Reset()         { *m = UserReq{} }
func (m *UserReq) String() string { return proto.CompactTextString(m) }
func (*UserReq) ProtoMessage()    {}
func (*UserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

func (m *UserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReq.Unmarshal(m, b)
}
func (m *UserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReq.Marshal(b, m, deterministic)
}
func (m *UserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReq.Merge(m, src)
}
func (m *UserReq) XXX_Size() int {
	return xxx_messageInfo_UserReq.Size(m)
}
func (m *UserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserReq proto.InternalMessageInfo

func (m *UserReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserReq) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"id,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=Account,proto3" json:"account,omitempty"`
	Showname             string   `protobuf:"bytes,3,opt,name=Showname,proto3" json:"showname,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=Email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *User) GetShowname() string {
	if m != nil {
		return m.Showname
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UserRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"success,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"msg,omitempty"`
	User                 *User    `protobuf:"bytes,3,opt,name=User,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRes) Reset()         { *m = UserRes{} }
func (m *UserRes) String() string { return proto.CompactTextString(m) }
func (*UserRes) ProtoMessage()    {}
func (*UserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{2}
}

func (m *UserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRes.Unmarshal(m, b)
}
func (m *UserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRes.Marshal(b, m, deterministic)
}
func (m *UserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRes.Merge(m, src)
}
func (m *UserRes) XXX_Size() int {
	return xxx_messageInfo_UserRes.Size(m)
}
func (m *UserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserRes proto.InternalMessageInfo

func (m *UserRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UserRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *UserRes) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UserListRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"success,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"msg,omitempty"`
	Users                []*User  `protobuf:"bytes,3,rep,name=Users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListRes) Reset()         { *m = UserListRes{} }
func (m *UserListRes) String() string { return proto.CompactTextString(m) }
func (*UserListRes) ProtoMessage()    {}
func (*UserListRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{3}
}

func (m *UserListRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListRes.Unmarshal(m, b)
}
func (m *UserListRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListRes.Marshal(b, m, deterministic)
}
func (m *UserListRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListRes.Merge(m, src)
}
func (m *UserListRes) XXX_Size() int {
	return xxx_messageInfo_UserListRes.Size(m)
}
func (m *UserListRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserListRes proto.InternalMessageInfo

func (m *UserListRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UserListRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *UserListRes) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*UserReq)(nil), "myserver.UserReq")
	proto.RegisterType((*User)(nil), "myserver.User")
	proto.RegisterType((*UserRes)(nil), "myserver.UserRes")
	proto.RegisterType((*UserListRes)(nil), "myserver.UserListRes")
}

func init() {
	proto.RegisterFile("server.proto", fileDescriptor_ad098daeda4239f7)
}

var fileDescriptor_ad098daeda4239f7 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x6d, 0xb3, 0xad, 0x89, 0x53, 0x29, 0x3a, 0x28, 0x2c, 0x3d, 0x95, 0xc5, 0x83, 0xa7, 0x88,
	0xf5, 0xe2, 0xd5, 0x83, 0x48, 0xa1, 0x1e, 0x4c, 0xf0, 0xe0, 0x49, 0xda, 0x74, 0xd0, 0x80, 0x69,
	0xec, 0x4e, 0xa2, 0xe4, 0xef, 0x65, 0x67, 0x1b, 0x41, 0x9b, 0x8b, 0xa7, 0x9d, 0x37, 0x6f, 0xde,
	0x7b, 0xb3, 0xbb, 0x70, 0xc4, 0x64, 0x3f, 0xc9, 0xc6, 0x1f, 0xb6, 0xac, 0x4a, 0x8c, 0x8a, 0xc6,
	0x63, 0x73, 0x09, 0xe1, 0x13, 0x93, 0x4d, 0x68, 0x8b, 0x63, 0x08, 0xe6, 0x6b, 0xdd, 0x9f, 0xf6,
	0x2f, 0x54, 0x12, 0xcc, 0xd7, 0x78, 0x0a, 0xc3, 0x45, 0x5e, 0xe4, 0x95, 0x0e, 0xa4, 0xe5, 0x81,
	0x59, 0xc1, 0xc0, 0x09, 0xf6, 0xa6, 0x35, 0x84, 0xb7, 0x59, 0x56, 0xd6, 0x1b, 0x3f, 0x7f, 0x98,
	0xb4, 0x10, 0x27, 0x10, 0xa5, 0x6f, 0xe5, 0xd7, 0x66, 0x59, 0x90, 0x56, 0x42, 0xfd, 0x60, 0x97,
	0x71, 0x57, 0x2c, 0xf3, 0x77, 0x3d, 0x10, 0xc2, 0x03, 0xf3, 0xdc, 0x2e, 0xc5, 0xce, 0x36, 0xad,
	0xb3, 0x8c, 0x98, 0x25, 0x2b, 0x4a, 0x5a, 0x88, 0xc7, 0xa0, 0x1e, 0xf8, 0x75, 0x17, 0xe6, 0x4a,
	0x34, 0x7e, 0x35, 0x09, 0x19, 0xcd, 0xc6, 0x71, 0x7b, 0xc9, 0x58, 0xcc, 0x84, 0x33, 0x2f, 0x30,
	0x72, 0xe7, 0x22, 0xe7, 0xea, 0xbf, 0xf6, 0xe7, 0x30, 0x74, 0x52, 0xd6, 0x6a, 0xaa, 0x3a, 0xfc,
	0x3d, 0x39, 0x6b, 0x00, 0x5c, 0x91, 0x0a, 0x83, 0x37, 0x00, 0x8f, 0x35, 0xd9, 0x46, 0x38, 0x3c,
	0xf9, 0x23, 0xa1, 0xed, 0xe4, 0xec, 0x77, 0x6b, 0xb7, 0x97, 0xe9, 0xe1, 0x15, 0x84, 0xf7, 0x54,
	0xc9, 0x53, 0x77, 0xc8, 0xf6, 0x5a, 0x6c, 0x7a, 0xab, 0x03, 0xf9, 0xdc, 0xeb, 0xef, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xc3, 0x96, 0xb1, 0x05, 0xec, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServerClient is the client API for UserServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServerClient interface {
	// 定义rpc端点
	QueryUsers(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserListRes, error)
	GetUser(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserRes, error)
}

type userServerClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServerClient(cc grpc.ClientConnInterface) UserServerClient {
	return &userServerClient{cc}
}

func (c *userServerClient) QueryUsers(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserListRes, error) {
	out := new(UserListRes)
	err := c.cc.Invoke(ctx, "/myserver.UserServer/QueryUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServerClient) GetUser(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserRes, error) {
	out := new(UserRes)
	err := c.cc.Invoke(ctx, "/myserver.UserServer/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServerServer is the server API for UserServer service.
type UserServerServer interface {
	// 定义rpc端点
	QueryUsers(context.Context, *UserReq) (*UserListRes, error)
	GetUser(context.Context, *UserReq) (*UserRes, error)
}

// UnimplementedUserServerServer can be embedded to have forward compatible implementations.
type UnimplementedUserServerServer struct {
}

func (*UnimplementedUserServerServer) QueryUsers(ctx context.Context, req *UserReq) (*UserListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryUsers not implemented")
}
func (*UnimplementedUserServerServer) GetUser(ctx context.Context, req *UserReq) (*UserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}

func RegisterUserServerServer(s *grpc.Server, srv UserServerServer) {
	s.RegisterService(&_UserServer_serviceDesc, srv)
}

func _UserServer_QueryUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServerServer).QueryUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/myserver.UserServer/QueryUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServerServer).QueryUsers(ctx, req.(*UserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserServer_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServerServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/myserver.UserServer/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServerServer).GetUser(ctx, req.(*UserReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "myserver.UserServer",
	HandlerType: (*UserServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryUsers",
			Handler:    _UserServer_QueryUsers_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserServer_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
