ServerConfigs:
  - IpAddr: 192.168.0.95
    Port: 8848
ClientConfig:
  NamespaceId: "7bf7d05a-b1ad-4e1e-806a-9daff4b3e4c0"
  TimeoutMs: 50000
  NotLoadCacheAtStart: true
  LogDir: "logs/nacos"
  LogLevel: "debug"
  ListenInterval: 30000
  BeatInterval: 5000
ConfigId: "gingate-dev.yaml"
Group: "dev"
SharedConfigs:
  - DataId: "share-mysql-dev.yaml"
    Group: "dev"
    Refresh: false
  - DataId: "share-redis-dev.yaml"
    Group: "dev"
    Refresh: false
  - DataId: "share-bizerr-dev.yaml"
    Group: "dev"
    Refresh: true