cfg:
  appName: "GatePro"
  releaseMode: false
  port: ":12000"
corsSettings:
  AllowOrigins:
    - "*"
  AllowMethods:
    - "OPTIONS"
    - "POST"
    - "GET"
grpcSettings:
  userServer: "127.0.0.1:12100"
  articleServer: "127.0.0.1:12200"
